name = "mayday-police-mdt-api"
main = "worker/index.js"
compatibility_date = "2026-06-17"

[[d1_databases]]
binding = "DB"
database_name = "mayday-police-mdt"
database_id = "ISI_DATABASE_ID_D1"

[[r2_buckets]]
binding = "R2"
bucket_name = "mayday-police-mdt-evidence"

[vars]
DEFAULT_GUILD_ID = "ISI_ID_SERVER_DISCORD"
BOT_WEBHOOK_URL = "https://domain-hosting-bot-kamu.com/worker-event"
BOT_API_SECRET = "buat_secret_panjang_random"
