import "dotenv/config";
import { Client, GatewayIntentBits, Partials, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, Events, SlashCommandBuilder, PermissionFlagsBits, ChannelType, REST, Routes } from "discord.js";
import { createClient } from "@supabase/supabase-js";
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers],partials:[Partials.Channel]});
const supabase=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);
const choices=["verifikasi_user","laporan_operasi","payroll","audit_log","propam_log","absensi_casis","absensi_sabhara","absensi_satbrimob","absensi_satlantas","absensi_polairud","absensi_bareskrim","absensi_setum","absensi_bidpropam"];
const commands=[new SlashCommandBuilder().setName("setup").setDescription("Set channel Mayday MDT").setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addStringOption(o=>o.setName("tipe").setDescription("Jenis channel").setRequired(true).addChoices(...choices.map(v=>({name:v,value:v})))).addChannelOption(o=>o.setName("channel").setDescription("Pilih channel").setRequired(true).addChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement)),new SlashCommandBuilder().setName("settings").setDescription("Lihat setting channel").setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild)].map(c=>c.toJSON());
async function register(){const rest=new REST({version:"10"}).setToken(process.env.DISCORD_BOT_TOKEN);await rest.put(Routes.applicationGuildCommands(process.env.DISCORD_CLIENT_ID,process.env.DISCORD_GUILD_ID),{body:commands})}
client.once(Events.ClientReady,async()=>{console.log(`Bot online: ${client.user.tag}`);await register();watchAttendance()});
client.on(Events.InteractionCreate,async i=>{try{if(i.isChatInputCommand()){if(i.commandName==="setup"){let tipe=i.options.getString("tipe",true),ch=i.options.getChannel("channel",true);let {error}=await supabase.from("bot_settings").upsert({guild_id:i.guildId,setting_key:tipe,setting_value:ch.id},{onConflict:"guild_id,setting_key"});if(error)throw error;return i.reply({content:`✅ ${tipe} diset ke ${ch}`,ephemeral:true})}if(i.commandName==="settings"){let {data}=await supabase.from("bot_settings").select("*").eq("guild_id",i.guildId);let desc=(data||[]).map(s=>`• **${s.setting_key}** → <#${s.setting_value}>`).join("\\n")||"Belum ada.";return i.reply({embeds:[new EmbedBuilder().setTitle("⚙️ MAYDAY MDT SETTINGS").setDescription(desc).setColor(0x2563eb)],ephemeral:true})}}if(i.isButton()){let [action,type,id]=i.customId.split(":"),status=action==="approve"?"APPROVED":"REJECTED";if(type!=="absensi")return;let {error}=await supabase.from("attendance").update({status,approved_by:i.user.id}).eq("id",Number(id));if(error)throw error;await i.update({content:`${status==="APPROVED"?"✅":"❌"} ABSENSI #${id} ${status} oleh ${i.user}.`,embeds:i.message.embeds,components:[]})}}catch(e){console.error(e);if(!i.replied)i.reply({content:`❌ ${e.message}`,ephemeral:true})}});
function watchAttendance(){supabase.channel("attendance-watch").on("postgres_changes",{event:"INSERT",schema:"public",table:"attendance"},p=>sendAttendance(p.new)).subscribe(s=>console.log("realtime:",s))}
async function setting(key){let {data}=await supabase.from("bot_settings").select("setting_value").eq("guild_id",process.env.DISCORD_GUILD_ID).eq("setting_key",key).maybeSingle();return data?.setting_value}
async function sendAttendance(r){let key=`absensi_${String(r.divisi||"CASIS").toLowerCase()}`,chId=await setting(key)||await setting("audit_log");if(!chId)return console.log("Channel belum diset",key);let ch=await client.channels.fetch(chId);let emb=new EmbedBuilder().setTitle("📋 ABSENSI ANGGOTA").setColor(0x22c55e).addFields({name:"Nama",value:r.nama||"-",inline:true},{name:"Jabatan",value:r.jabatan||"-",inline:true},{name:"Divisi",value:r.divisi||"-",inline:true},{name:"Status",value:r.type||"-",inline:true},{name:"Keterangan",value:r.note||"-"}).setFooter({text:`Record ID: ${r.id}`}).setTimestamp();if(r.evidence_url)emb.setImage(r.evidence_url);let row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`approve:absensi:${r.id}`).setLabel("ACC").setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`reject:absensi:${r.id}`).setLabel("TOLAK").setStyle(ButtonStyle.Danger));let msg=await ch.send({embeds:[emb],components:[row]});try{let th=await msg.startThread({name:`${r.nama||"Anggota"} - ${r.divisi||"DIVISI"}`,autoArchiveDuration:10080});await supabase.from("attendance").update({discord_message_id:msg.id,discord_thread_id:th.id}).eq("id",r.id)}catch{}}
client.login(process.env.DISCORD_BOT_TOKEN);
