import { supabase } from "./supabase.js";
const state={page:"home",user:null,profile:null,members:[],attendance:[],reports:[],propam:[]};
const app=document.querySelector("#app");
function setPage(p){state.page=p;render()}
async function init(){const {data}=await supabase.auth.getUser();state.user=data.user;if(state.user){await ensureProfile();await loadData()}render()}
async function loginDiscord(){await supabase.auth.signInWithOAuth({provider:"discord",options:{redirectTo:window.location.origin}})}
async function logout(){await supabase.auth.signOut();location.reload()}
async function ensureProfile(){const u=state.user, meta=u.user_metadata||{}, discordId=meta.provider_id||u.identities?.[0]?.identity_data?.sub||u.id;let {data:p}=await supabase.from("profiles").select("*").eq("auth_user_id",u.id).maybeSingle();if(!p){let res=await supabase.from("profiles").insert({auth_user_id:u.id,discord_id:discordId,display_name:meta.full_name||meta.name||u.email||"Unknown",avatar_url:meta.avatar_url||"/logo.png",jabatan:"CASIS",divisi:"CASIS",status:"PENDING"}).select("*").single();if(res.error)throw res.error;p=res.data}state.profile=p}
async function loadData(){let [m,a,r,d]=await Promise.all([supabase.from("profiles").select("*").order("created_at",{ascending:false}),supabase.from("attendance").select("*").order("created_at",{ascending:false}).limit(50),supabase.from("reports").select("*").order("created_at",{ascending:false}).limit(50),supabase.from("disciplinary_records").select("*").order("created_at",{ascending:false}).limit(50)]);state.members=m.data||[];state.attendance=a.data||[];state.reports=r.data||[];state.propam=d.data||[]}
function top(t){return `<header class="topbar"><h1>${t}</h1><img class="avatar" src="${state.profile?.avatar_url||"/logo.png"}"/></header>`}
function nav(){return `<nav class="nav">${[["home","🏠","HOME"],["log","↺","LOG"],["payroll","💵","GAJI"],["book","▣","BUKU"],["admin","⚙","ADMIN"]].map(([id,ic,tx])=>`<button class="${state.page===id?'active':''}" onclick="setPage('${id}')"><span>${ic}</span>${tx}</button>`).join("")}</nav>`}
function loginPage(){app.innerHTML=`<main class="app login-screen"><section class="login-frame"><div class="login-head">OFFICIAL MDT V1.0</div><div class="logo-wrap"><img src="/logo.png" class="logo"/><h2 class="big-title">MAYDAY<br><span style="color:#2563eb">POLICE</span></h2><div class="badge">MOBILE DATA TERMINAL</div></div><button class="btn" onclick="loginDiscord()">LOGIN DISCORD</button><p class="notice">Login pakai Discord OAuth via Supabase.</p><div class="warning">AKSES TANPA IZIN AKAN DILACAK BIDPROPAM.</div></section></main>`}
function pending(){return `${top("ACCOUNT VERIFICATION")}<main class="page"><section class="card yellow"><h2>AKUN PENDING</h2><p>Menunggu ACC dari PAMA/PAMEN/PATI/Admin.</p><button class="btn red" onclick="logout()">LOGOUT</button></section><section class="card"><div class="kv"><div><small>NAMA</small><strong>${state.profile.display_name}</strong></div><div><small>JABATAN</small><strong>${state.profile.jabatan}</strong></div><div><small>DIVISI</small><strong>${state.profile.divisi}</strong></div></div></section></main>`}
function home(){let p=state.profile;return `${top("PERSONNEL TERMINAL")}<main class="page"><section class="card blue"><span class="badge">AKSES TERVERIFIKASI</span><h2 class="big-title">${p.display_name.toUpperCase()}</h2><button class="btn yellow">${p.jabatan}</button><button class="btn">${p.divisi} • ${p.badge_number||"#0000"}</button></section><section class="grid"><div class="card yellow"><h3>REPUTATION</h3><div class="big-title">${p.prp||0}</div><p>POINTS</p></div><div class="card green"><h3>DUTY</h3><div class="big-title">${state.attendance.length}</div><p>RECORDS</p></div></section><section class="grid"><button class="tile" onclick="setPage('absensi')"><div class="icon">📷</div>ABSENSI</button><button class="tile" onclick="setPage('laporan')"><div class="icon">📄</div>LAPORAN</button><button class="tile" onclick="setPage('propam')"><div class="icon">⚖️</div>BIDPROPAM</button><button class="tile" onclick="setPage('anggota')"><div class="icon">👮</div>ANGGOTA</button></section></main>${nav()}`}
function absensi(){let p=state.profile;return `${top("ABSENSI")}<main class="page"><section class="card"><div class="kv"><div><small>NAMA</small><strong>${p.display_name}</strong></div><div><small>JABATAN</small><strong>${p.jabatan}</strong></div><div><small>DIVISI</small><strong>${p.divisi}</strong></div></div><div class="field"><label>Jenis</label><select id="absType"><option>HADIR</option><option>IZIN</option><option>CUTI</option></select></div><div class="field"><label>Keterangan</label><textarea id="absNote"></textarea></div><div class="field"><label>Bukti Foto</label><input id="absFile" type="file" accept="image/*"/></div><button class="btn green" onclick="submitAbsensi()">KIRIM ABSENSI</button></section></main>`}
async function upload(file,folder){if(!file)return null;let ext=file.name.split(".").pop(),path=`${folder}/${state.profile.id}-${Date.now()}.${ext}`;let {error}=await supabase.storage.from("evidence").upload(path,file);if(error)throw error;return supabase.storage.from("evidence").getPublicUrl(path).data.publicUrl}
async function submitAbsensi(){let file=document.querySelector("#absFile").files[0],url=await upload(file,"attendance"),p=state.profile;let {error}=await supabase.from("attendance").insert({user_id:p.id,discord_id:p.discord_id,nama:p.display_name,jabatan:p.jabatan,divisi:p.divisi,type:document.querySelector("#absType").value,note:document.querySelector("#absNote").value||"-",evidence_url:url,status:"PENDING"});if(error)return alert(error.message);await loadData();alert("Absensi masuk.");setPage("log")}
function laporan(){return `${top("LAPORAN OPS")}<main class="page"><section class="grid">${["PENANGKAPAN","KASUS BESAR","PATROLI","BACKUP","PENILANGAN","ADMINISTRASI"].map(x=>`<button class="tile" onclick="openLaporan('${x}')"><div class="icon">📄</div>${x}</button>`).join("")}</section></main>`}
function openLaporan(x){state.currentReport=x;state.page="laporanForm";render()}
function laporanForm(){return `${top(state.currentReport)}<main class="page"><section class="card"><div class="field"><label>Lokasi</label><input id="repLoc"/></div><div class="field"><label>Kronologi</label><textarea id="repText"></textarea></div><div class="field"><label>Bukti</label><input id="repFile" type="file" accept="image/*"/></div><button class="btn" onclick="submitReport()">KIRIM LAPORAN</button></section></main>`}
async function submitReport(){let file=document.querySelector("#repFile").files[0],url=await upload(file,"reports"),p=state.profile;let {error}=await supabase.from("reports").insert({user_id:p.id,type:state.currentReport,nama:p.display_name,divisi:p.divisi,payload:{location:document.querySelector("#repLoc").value,report:document.querySelector("#repText").value},evidence_url:url,status:"PENDING"});if(error)return alert(error.message);await loadData();alert("Laporan masuk.");setPage("log")}
function propam(){return `${top("BIDPROPAM")}<main class="page"><section class="card dark"><h2>SP / PTDH</h2><p class="notice">SP1 → SP2 → SP3 → PTDH.</p></section><section class="card"><div class="field"><label>Target</label><select id="spTarget">${state.members.map(m=>`<option value="${m.id}">${m.display_name}</option>`).join("")}</select></div><div class="field"><label>Level</label><select id="spLevel"><option>1</option><option>2</option><option>3</option><option>99</option></select></div><div class="field"><label>Alasan</label><textarea id="spReason"></textarea></div><button class="btn red" onclick="submitSP()">KIRIM</button></section></main>`}
async function submitSP(){let id=Number(document.querySelector("#spTarget").value),t=state.members.find(m=>m.id===id);let {error}=await supabase.from("disciplinary_records").insert({target_user_id:id,target_name:t?.display_name,issued_by:state.profile.display_name,sp_level:Number(document.querySelector("#spLevel").value),reason:document.querySelector("#spReason").value,status:"ACTIVE"});if(error)return alert(error.message);await loadData();setPage("log")}
function anggota(){return `${top("DATA ANGGOTA")}<main class="page"><section class="card"><table class="table">${state.members.map(m=>`<tr><td>${m.display_name}<br><span class="status pending">${m.status}</span></td><td>${m.jabatan}</td><td>${m.divisi}</td></tr>`).join("")}</table></section></main>`}
function log(){return `${top("ACTIVITY LOG")}<main class="page"><section class="card"><h2>Absensi</h2>${table(state.attendance)}</section><section class="card"><h2>Laporan</h2>${table(state.reports)}</section><section class="card"><h2>Propam</h2>${table(state.propam)}</section></main>${nav()}`}
function table(rows){return rows.length?`<table class="table">${rows.map(r=>`<tr><td>${r.type||("SP"+r.sp_level)}</td><td>${r.divisi||r.target_name||""}</td><td><span class="status pending">${r.status}</span></td></tr>`).join("")}</table>`:`<div class="empty"><h2>NIHIL DATA</h2></div>`}
function payroll(){return `${top("FINANCIAL GATEWAY")}<main class="page"><section class="card blue"><span class="badge">FINANCE SYSTEM READY</span><h2 class="big-title">PAYROLL</h2></section><section class="card green"><h3>BASE SALARY</h3><h2 class="big-title">$100.000</h2></section></main>${nav()}`}
function book(){return `${top("DIVISIONAL HANDBOOK")}<main class="page"><section class="card"><h2>📘 BUKU SAKU DIVISI</h2><div class="badge">AKSES: ${state.profile.divisi}</div></section></main>${nav()}`}
function admin(){return `${top("ADMIN PANEL")}<main class="page"><section class="card dark"><h2>PENDING USER</h2>${state.members.filter(m=>m.status==="PENDING").map(m=>`<div class="card"><b>${m.display_name}</b><br>${m.jabatan} • ${m.divisi}<button class="btn green" onclick="approve(${m.id})">ACC</button><button class="btn red" onclick="reject(${m.id})">TOLAK</button></div>`).join("")||"Tidak ada pending."}</section></main>${nav()}`}
async function approve(id){await supabase.from("profiles").update({status:"ACTIVE",jabatan:"CASIS",divisi:"CASIS"}).eq("id",id);await loadData();render()}
async function reject(id){await supabase.from("profiles").update({status:"REJECTED"}).eq("id",id);await loadData();render()}
function render(){if(!state.user)return loginPage();if(state.profile?.status!=="ACTIVE"){app.innerHTML=`<main class="app">${pending()}</main>`;return}let map={home,absensi,laporan,laporanForm,propam,anggota,log,payroll,book,admin};app.innerHTML=`<main class="app">${map[state.page]()}</main>`}
Object.assign(window,{setPage,loginDiscord,logout,submitAbsensi,openLaporan,submitReport,submitSP,approve,reject});init().catch(e=>{console.error(e);app.innerHTML=`<main class="app page"><section class="card"><h2>Error</h2><p>${e.message}</p></section></main>`});
